"""
Tutor plugin: landa_course_files
=================================
Thêm LMS API endpoint:

  GET /api/landa/v0/course_files/{course_id}/

Trả về danh sách tất cả file UNLOCKED (locked=False) của course.
Chỉ enrolled user (hoặc staff) mới gọi được.

Admin workflow:
  Studio → Files & Uploads → Upload file → Click ổ khóa để Unlock → Xong!
  (Không cần viết HTML vào Course Handouts)

FE workflow:
  useCourseFiles(courseId) → fetch /api/landa/v0/course_files/{id}/
  → hiển thị danh sách file trong sidebar "Tài liệu tham khảo"
"""

from tutor import hooks

# ── Django app code được inject vào LMS bằng ENV_PATCHES ──
# Dùng openedx-lms-production-settings để code chạy cả dev lẫn production.

VIEWS_CODE = '''
# ============================================================
# LANDA Course Files API — auto-generated by landa_course_files plugin
# ============================================================
import json
import logging

from django.http import JsonResponse
from django.views import View
from django.views.decorators.http import require_http_methods
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt

from opaque_keys.edx.keys import CourseKey
from opaque_keys import InvalidKeyError

from common.djangoapps.student.models import CourseEnrollment
from xmodule.contentstore.django import contentstore as get_contentstore
from xmodule.modulestore.django import modulestore

log = logging.getLogger(__name__)

DOCUMENT_EXTENSIONS = {
    "pdf", "doc", "docx", "ppt", "pptx",
    "xls", "xlsx", "csv", "txt", "zip", "rar"
}

def _get_extension(filename):
    if "." not in filename:
        return ""
    return filename.rsplit(".", 1)[-1].lower()

def _is_document(filename):
    return _get_extension(filename) in DOCUMENT_EXTENSIONS


class CourseFilesView(View):
    """
    GET /api/landa/v0/course_files/{course_id}/

    Trả về danh sách file unlocked (locked=False) của course.
    Yêu cầu: user đã đăng nhập VÀ (enrolled hoặc is_staff).

    Response JSON:
    {
        "files": [
            {
                "id": "asset-v1:Org+Course+Run+type@asset+block@file.pdf",
                "display_name": "Slide Tuan 1.pdf",
                "url": "/asset-v1:Org+Course+Run+type@asset+block@file.pdf",
                "extension": "pdf",
                "content_type": "application/pdf",
                "size": 204800,
                "date_added": "2026-04-29T10:00:00Z"
            }
        ],
        "total": 1
    }
    """

    CONTENT_TYPE_MAP = {
        "pdf":  "application/pdf",
        "doc":  "application/msword",
        "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "ppt":  "application/vnd.ms-powerpoint",
        "pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "xls":  "application/vnd.ms-excel",
        "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "csv":  "text/csv",
        "txt":  "text/plain",
        "zip":  "application/zip",
    }

    def get(self, request, course_id):
        # 1. Auth check
        if not request.user or not request.user.is_authenticated:
            return JsonResponse({"error": "Authentication required"}, status=401)

        # 2. Parse course key
        try:
            course_key = CourseKey.from_string(course_id)
        except (InvalidKeyError, ValueError):
            return JsonResponse({"error": "Invalid course_id"}, status=400)

        # 3. Enrollment / staff check
        user = request.user
        if not user.is_staff:
            enrolled = CourseEnrollment.is_enrolled(user, course_key)
            if not enrolled:
                return JsonResponse(
                    {"error": "You must be enrolled in this course"},
                    status=403
                )

        # 4. Query contentstore for all assets
        try:
            cs = get_contentstore()
            assets, _ = cs.get_all_content_for_course(course_key)
        except Exception as exc:
            log.exception("landa_course_files: error fetching assets for %s: %s", course_id, exc)
            return JsonResponse({"error": "Failed to fetch course assets"}, status=500)

        # 5. Filter unlocked document files
        result = []
        for asset in assets:
            if asset.get("locked", True):
                continue  # skip locked files

            name = asset.get("display_name", "")
            ext = _get_extension(name)
            if not _is_document(name):
                continue  # skip images, videos, etc.

            asset_id = str(asset.get("asset_key", ""))
            # Build relative URL from asset_key
            # asset_key format: asset-v1:Org+Course+Run+type@asset+block@filename
            url = "/" + asset_id if asset_id else ""

            result.append({
                "id": asset_id,
                "display_name": name,
                "url": url,
                "extension": ext,
                "content_type": self.CONTENT_TYPE_MAP.get(ext, "application/octet-stream"),
                "size": asset.get("size", 0),
                "date_added": str(asset.get("uploadDate", "")),
            })

        # Sort by date_added desc (newest first)
        result.sort(key=lambda x: x["date_added"], reverse=True)

        return JsonResponse({"files": result, "total": len(result)})
'''

URLS_CODE = '''
# LANDA Course Files URLs — auto-generated by landa_course_files plugin
from django.urls import re_path
from django.conf import settings

# Import view được định nghĩa trong lms-common-settings patch
# Vì không phải Django app riêng, dùng lazy import
def _get_view():
    from lms.djangoapps.landa_api.views import CourseFilesView
    return CourseFilesView.as_view()

# Không dùng được lazy import trực tiếp trong urlpatterns
# Dùng cách inject view trực tiếp trong settings patch thay thế
'''

# Inject view code vào LMS settings
hooks.Filters.ENV_PATCHES.add_items([
    (
        "openedx-lms-common-settings",
        """
# ── LANDA Course Files API ──
# View code được load inline, không cần Django app riêng.
# Inject vào LMS_ROOT_URLCONF thông qua URL patch bên dưới.
LANDA_COURSE_FILES_ENABLED = True
"""
    ),
])

# Inject URL pattern vào LMS urls.py
hooks.Filters.ENV_PATCHES.add_items([
    (
        "openedx-lms-urls",
        """
# LANDA Course Files API
try:
    from django.urls import re_path, path
    from django.http import JsonResponse
    from django.views import View
    import logging as _logging
    from opaque_keys.edx.keys import CourseKey
    from opaque_keys import InvalidKeyError
    from common.djangoapps.student.models import CourseEnrollment
    from xmodule.contentstore.django import contentstore as _get_contentstore

    _log = _logging.getLogger("landa.course_files")

    _DOCUMENT_EXTENSIONS = {
        "pdf", "doc", "docx", "ppt", "pptx",
        "xls", "xlsx", "csv", "txt", "zip"
    }

    _CONTENT_TYPE_MAP = {
        "pdf":  "application/pdf",
        "doc":  "application/msword",
        "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "ppt":  "application/vnd.ms-powerpoint",
        "pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "xls":  "application/vnd.ms-excel",
        "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "csv":  "text/csv",
        "txt":  "text/plain",
        "zip":  "application/zip",
    }

    def _ext(name):
        return name.rsplit(".", 1)[-1].lower() if "." in name else ""

    def _is_doc(name):
        return _ext(name) in _DOCUMENT_EXTENSIONS

    class _CourseFilesView(View):
        def get(self, request, course_id):
            if not request.user or not request.user.is_authenticated:
                return JsonResponse({"error": "Authentication required"}, status=401)
            try:
                course_key = CourseKey.from_string(course_id)
            except (InvalidKeyError, ValueError):
                return JsonResponse({"error": "Invalid course_id"}, status=400)
            user = request.user
            if not user.is_staff:
                if not CourseEnrollment.is_enrolled(user, course_key):
                    return JsonResponse({"error": "Enrollment required"}, status=403)
            try:
                cs = _get_contentstore()
                assets, _ = cs.get_all_content_for_course(course_key)
            except Exception as exc:
                _log.exception("landa course_files error: %s", exc)
                return JsonResponse({"error": "Server error"}, status=500)
            result = []
            for asset in assets:
                if asset.get("locked", True):
                    continue
                name = asset.get("display_name", "")
                if not _is_doc(name):
                    continue
                ext = _ext(name)
                asset_id = str(asset.get("asset_key", ""))
                url = "/" + asset_id if asset_id else ""
                result.append({
                    "id": asset_id,
                    "display_name": name,
                    "url": url,
                    "extension": ext,
                    "content_type": _CONTENT_TYPE_MAP.get(ext, "application/octet-stream"),
                    "size": asset.get("size", 0),
                    "date_added": str(asset.get("uploadDate", "")),
                })
            result.sort(key=lambda x: x["date_added"], reverse=True)
            return JsonResponse({"files": result, "total": len(result)})

    urlpatterns += [
        re_path(
            r"^api/landa/v0/course_files/(?P<course_id>[^/]+)/$",
            _CourseFilesView.as_view(),
            name="landa_course_files",
        ),
    ]
    _log.info("LANDA Course Files API registered at /api/landa/v0/course_files/")

except Exception as _e:
    import logging as _l
    _l.getLogger("landa.course_files").error("Failed to register landa course_files API: %s", _e)
"""
    ),
])
